/* 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number
*/
console.log('Number.isFinite()')
console.log(Number.isFinite('1')) //!!!!!! false
console.log(Number.isFinite('aaa'))
console.log(Number.isFinite(1))
console.log(Number.isFinite(-1))
console.log(Number.isFinite(1.1))
console.log(Number.isFinite(-1.1))
console.log(Number.isFinite(0))
console.log(Number.isFinite(Infinity))
console.log(Number.isFinite(-Infinity))
console.log(Number.isFinite(NaN))
console.log(Number.isFinite(undefined))

console.log('------------------')
console.log('isFinite()')

console.log(isFinite('1')) //!!!!! true
console.log(isFinite('aaa'))
console.log(isFinite(1))
console.log(isFinite(-1))
console.log(isFinite(1.1))
console.log(isFinite(-1.1))
console.log(isFinite(0))
console.log(isFinite(Infinity))
console.log(isFinite(-Infinity))
console.log(isFinite(NaN))
console.log(isFinite(undefined))

console.log('------------------')
console.log('isNaN()')

console.log(isNaN('1'))
console.log(isNaN('aaa'))
console.log(isNaN(1))
console.log(isNaN(-1))
console.log(isNaN(1.1))
console.log(isNaN(-1.1))
console.log(isNaN(0))
console.log(isNaN(Infinity))
console.log(isNaN(-Infinity))
console.log(isNaN(NaN))
console.log(isNaN(undefined))

console.log('------------------')
console.log('parseInt()')

console.log(parseInt('1'))
console.log(parseInt('aaa'))
console.log(parseInt('123aaa123'))
console.log(parseInt('aaa321'))
console.log(parseInt(1))
console.log(parseInt(-1))
console.log(parseInt(1.1))
console.log(parseInt(-1.1))
console.log(parseInt(0))
console.log(parseInt(Infinity))
console.log(parseInt(-Infinity))
console.log(parseInt(NaN))
console.log(parseInt(undefined))
console.log(parseInt('123e7'))

console.log('------------------')
console.log('parseFloat()')

console.log(parseFloat('1'))
console.log(parseFloat('aaa'))
console.log(parseFloat('123aaa123'))
console.log(parseFloat('aaa321'))
console.log(parseFloat(1))
console.log(parseFloat(-1))
console.log(parseFloat(1.1))
console.log(parseFloat(-1.1))
console.log(parseFloat(0))
console.log(parseFloat(Infinity))
console.log(parseFloat(-Infinity))
console.log(parseFloat(NaN))
console.log(parseFloat(undefined))
console.log(parseFloat('123e7'))

console.log('------------------')
console.log('toFixed()')

//console.log(('1').toFixed(1)) klaida
console.log((1.5).toFixed(1))
console.log((1.5).toFixed(0))
console.log((1.5).toFixed(5))
console.log((Infinity).toFixed(1))

